# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1bd5b012a3750b4ab1c6a522b5c443d4f6acdf8488679707e6474995e2f5eea22c29e4c326b35d1683fdfe3aa08c3a3a4bab5cabb9992fc743a5c0fd626d7827

test:
  secret_key_base: 592dae904356b564894bbbd90a527ee039c2ec3796d20556301d67eb7d4987d5744d0296f6d596462f56a416e31b97d64610c2b6af21887a5bfd7408a4922b16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
